name: 'Sysdig CIS Dockerfile Benchmark'
description: 'Run CIS Dockerfile benchmark against dockerfiles in repository (CIS 4.1, 4.2, 4.3, 4.6, 4.7, 4.9, 4.10)'
inputs:
  directory:
    description: 'Directory of dockerfiles'
    required: false
    default: './'
  dockerfilePattern:
    description: 'Dockerfile name pattern (case insensitive)'
    required: false
    default: 'dockerfile'
outputs:
  violation_report:
    description: 'CIS Dockerfile benchmark violation report'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.dockerfilePattern }}
branding:
  icon: alert-circle
  color: blue

