name: 'Sysdig CIS Dockerfile Benchmark'
description: 'Run CIS Dockerfile benchmark against dockerfiles in repository (CIS 4.1, 4.2, 4.3, 4.6, 4.7, 4.9, 4.10)'
inputs:
  directory:
    description: 'Directory of dockerfiles'
    required: false
    default: './'
  dockerfilePattern:
    description: 'Dockerfile name pattern (case insensitive)'
    required: false
    default: 'dockerfile'
  disallowedPackages:
    description: 'list of disallowed packages separated by comma'
    required: false
    default: ''
  trustedBaseImages:
    description: 'list of trusted base images separated by comma'
    required: false
    default: ''
  secretPatterns:
    description: 'list of secret patterns separated by comma'
    required: false
    default: ''
    
outputs:
  violation_report:
    description: 'CIS Dockerfile benchmark violation report'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.dockerfilePattern }}
    - ${{ inputs.disallowedPackages }}
    - ${{ inputs.trustedBaseImages }}
    - ${{ inputs.secretPatterns }}
branding:
  icon: alert-circle
  color: blue

